# Generated by Django 2.2.1 on 2019-07-28 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planninghistory', '0002_auto_20190728_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 28, 22, 0, 21, 126789)),
        ),
        migrations.AddField(
            model_name='place',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 28, 22, 0, 21, 126767)),
        ),
    ]
