# Generated by Django 2.2.1 on 2019-07-29 20:20

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('planninghistory', '0003_auto_20190728_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='place',
            name='start_date',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 29, 20, 20, 21, 642707, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
