# Generated by Django 2.2.1 on 2019-08-14 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planninghistory', '0005_event_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='user',
            new_name='traveler',
        ),
    ]
