# Generated by Django 2.2.1 on 2019-06-27 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorerapp', '0002_auto_20190626_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='city',
            name='length',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=60)),
                ('location_number', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, null=True)),
                ('length', models.DecimalField(decimal_places=8, max_digits=11, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorerapp.City')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='explorerapp.Address'),
        ),
    ]
