# Generated by Django 2.2.1 on 2019-06-29 21:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorerapp', '0003_auto_20190627_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='creation_date',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4, validators=[django.core.validators.MaxValueValidator(2019)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
    ]
