# Generated by Django 2.2.1 on 2019-06-30 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorerapp', '0006_auto_20190630_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='place',
        ),
        migrations.AddField(
            model_name='place',
            name='rating',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='explorerapp.Rating'),
            preserve_default=False,
        ),
    ]
