# Generated by Django 2.2.1 on 2019-06-30 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorerapp', '0007_auto_20190630_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='rating',
        ),
    ]
