# Generated by Django 2.2.1 on 2019-06-30 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorerapp', '0008_remove_place_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='rating',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='explorerapp.Rating'),
        ),
        migrations.AddField(
            model_name='rating',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='explorerapp.Place'),
            preserve_default=False,
        ),
    ]
