# Generated by Django 2.2.1 on 2019-06-30 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorerapp', '0009_auto_20190630_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='explorerapp.Rating'),
        ),
    ]
