# Generated by Django 2.2.1 on 2019-06-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorerapp', '0011_auto_20190630_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='rating',
            field=models.IntegerField(blank=True),
        ),
    ]
