# Generated by Django 2.2.1 on 2019-06-30 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorerapp', '0012_auto_20190630_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='place',
        ),
    ]
