# Generated by Django 2.2.1 on 2019-06-30 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorerapp', '0013_remove_rating_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.RemoveField(
            model_name='place',
            name='rating',
        ),
    ]
