# Generated by Django 2.2.1 on 2019-06-30 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorerapp', '0015_auto_20190630_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='rating',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings', to='explorerapp.Rating'),
        ),
    ]
