# Generated by Django 2.2.1 on 2019-06-30 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorerapp', '0016_auto_20190630_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='rating',
            field=models.ForeignKey(blank=True, default=5, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings', to='explorerapp.Rating'),
        ),
    ]
