# Generated by Django 2.2.1 on 2019-06-30 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorerapp', '0018_auto_20190630_2011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
